name: specs

on: [push]

jobs:
  run-specs:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.31.1

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Check build
        run: |
          crystal -v
          crystal build --release src/build.cr -o bin/crenv-install
          bin/crenv-install -v
      - name: Run tests
        run: |
          crystal -v
          crystal spec --order random
